<?php
    session_start();
    
        if(isset($_POST['gender']))
        {
            $_SESSION['g']=2;
        }
        if(empty($_POST['gender']))
        {
         $_SESSION['g']=1;
        }
        if(isset($_POST['dateofbirth']))
        {
            $_SESSION['db']=2;
        }
        if(empty($_POST['dateofbirth']))
        {
            $_SESSION['db']=1;
        }
        if(isset($_POST['pass_type']))
        {
            $_SESSION['ps']=2;
        }
        if(empty($_POST['pass_type']))
        {
            $_SESSION['ps']=1;
        }
        if(isset($_POST['birthidno']))
        {
            $_SESSION['bd']=2;
        }
        if(empty($_POST['birthidno']))
        {
            $_SESSION['bd']=1;
        }
        if(isset($_POST['height_cm']))
        {
            $_SESSION['hcm']=2;
        }
        if(empty($_POST['height_cm']))
        {
            $_SESSION['hcm']=1;
        } 
        if(isset($_POST['height_inch']))
        {
            $_SESSION['hin']=2;
        }
        if(empty($_POST['height_inch']))
        {
            $_SESSION['hin']=1;
        }
        if(isset($_POST['religion']))
        {
            $_SESSION['re']=2;
        }
        if(empty($_POST['religion']))
        {
            $_SESSION['re']=1;
        }
        if(isset($_POST['nameofapplicant']))
        {
            $_SESSION['nam']=2;
        }
        if(empty($_POST['nameofapplicant']))
        {
            $_SESSION['nam']=1;
        }
        if(isset($_POST['appliemail']))
        {
            $_SESSION['apm']=2;
        }
        if(empty($_POST['appliemail']))
        {
            $_SESSION['apm']=1;
        }
        if(isset($_POST['surnnameofapplicant']))
        {
            $_SESSION['sp']=2;
        }
        if(empty($_POST['surnnameofapplicant']))
        {
            $_SESSION['sp']=1;
        }
        if(isset($_POST['nameoffather']))
        {
            $_SESSION['gn']=2;
        }
        if(empty($_POST['nameoffather']))
        {
            $_SESSION['gn']=1;
        }
        if(isset($_POST['citizen_ship_type']))
        {
            $_SESSION['cit']=2;
        }
        if(empty($_POST['citizen_ship_type']))
        {
            $_SESSION['cit']=1;
        }
        if(isset($_POST['father_nationality']))
        {
            $_SESSION['fn']=2;
        }
        if(empty($_POST['father_nationality']))
        {
            $_SESSION['fn']=1;
        }
        if(isset($_POST['father_profession']))
        {
            $_SESSION['fp']=2;
        }
        if(empty($_POST['father_profession']))
        {
            $_SESSION['fp']=1;
        }
        if(isset($_POST['nameofmother']))
        {
            $_SESSION['mn']=2;
        }
        if(empty($_POST['nameofmother']))
        {
            $_SESSION['mn']=1;
        }
        if(isset($_POST['mother_nationality']))
        {
            $_SESSION['mni']=2;
        }
        if(empty($_POST['mother_nationality']))
        {
            $_SESSION['mni']=1;
        }
        if(isset($_POST['mother_profession']))
        {
            $_SESSION['mp']=2;
        }
        if(empty($_POST['mother_profession']))
        {
            $_SESSION['mp']=1;
        }
        if(isset($_POST['district']))
        {
            $_SESSION['d']=2;
        }
        if(empty($_POST['district']))
        {
            $_SESSION['d']=1;
        }
        if(isset($_POST['police']))
        {
            $_SESSION['po']=2;
        }
        if(empty($_POST['police']))
        {
            $_SESSION['po']=1;
        }
        if(isset($_POST['postoffice']))
        {
            $_SESSION['pos']=2;
        }
        if(empty($_POST['postoffice']))
        {
            $_SESSION['pos']=1;
        }
        if(isset($_POST['marital_status']))
        {
            $_SESSION['mts']=2;
        }
        if(empty($_POST['marital_status']))
        {
            $_SESSION['mts']=1;
        }
        if(isset($_POST['applicant_profession']))
        {
            $_SESSION['apf']=2;
        }
        if(empty($_POST['applicant_profession']))
        {
            $_SESSION['apf']=1;
        }
        if(isset($_POST['birth_country']))
        {
            $_SESSION['brc']=2;
        }
        if(empty($_POST['birth_country']))
        {
            $_SESSION['brc']=1;
        }
        if(isset($_POST['pmdistrict']))
        {
            $_SESSION['pmdis']=2;
        }
        if(empty($_POST['pmdistrict']))
        {
            $_SESSION['pmdis']=1;
        }
        if(isset($_POST['birthdistrict']))
        {
            $_SESSION['bdd']=2;
        }
        if(empty($_POST['birthdistrict']))
        {
            $_SESSION['bdd']=1;
        }
        if(isset($_POST['pmpolice']))
        {
            $_SESSION['pp']=2;
        }
        if(empty($_POST['pmpolice']))
        {
            $_SESSION['pp']=1;
        }
        if(isset($_POST['pmpostoffice']))
        {
            $_SESSION['ppos']=2;
        }
        if(empty($_POST['pmpostoffice']))
        {
            $_SESSION['ppos']=1;
        }
        if($_SESSION['g']==1||$_SESSION['db']==1||$_SESSION['ps']==1||$_SESSION['bd']==1||$_SESSION['hin']==1||$_SESSION['hcm']==1||$_SESSION['re']==1||$_SESSION['nam']==1||$_SESSION['apm']==1||$_SESSION['sp']==1||$_SESSION['gn']==1||$_SESSION['cit']==1||$_SESSION['fn']==1||$_SESSION['fp']==1||$_SESSION['mn']==1||$_SESSION['mni']==1||$_SESSION['mp']==1||$_SESSION['d']==1||$_SESSION['po']==1||$_SESSION['pos']==1||$_SESSION['mts']==1||$_SESSION['apf']==1||$_SESSION['brc']==1||$_SESSION['pmdis']==1||$_SESSION['bdd']==1||$_SESSION['pp']==1||$_SESSION['ppos']==1)
        {
         header('Location:index.php');
        }
        if($_SESSION['g']==2 && $_SESSION['db']==2 && $_SESSION['ps']==2 && $_SESSION['bd']==2 && $_SESSION['hcm']==2 && $_SESSION['hin']==2&& $_SESSION['re']==2&& $_SESSION['nam']==2&& $_SESSION['apm']==2 && $_SESSION['sp']==2&& $_SESSION['gn']==2&& $_SESSION['cit']==2&& $_SESSION['fn']==2&& $_SESSION['fp']==2&& $_SESSION['mn']==2&& $_SESSION['mni']==2&& $_SESSION['mp']==2&& $_SESSION['d']==2&& $_SESSION['po']==2&& $_SESSION['pos']==2&& $_SESSION['mts']==2&& $_SESSION['apf']==2&& $_SESSION['brc']==2&& $_SESSION['pmdis']==2&& $_SESSION['bdd']==2&& $_SESSION['pp']==2&& $_SESSION['ppos']==2)
        {
         header('Location:stage2.php');
        }

    
  