<?php
    session_start();
    $_SESSION['s1'];
    $_SESSION['dateofbirth']=test_input($_POST['dateofbirth']);
    $_SESSION['app_place']=test_input($_POST['app_place']);
    $_SESSION['gender']=test_input($_POST['gender']);
    $_SESSION['app_type']=test_input($_POST['app_type']);
    $_SESSION['pass_type']=test_input($_POST['pass_type']);
    $_SESSION['birthidno']=test_input($_POST['birthidno']);
    $_SESSION['niidno']=test_input($_POST['niidno']);
    $_SESSION['delivary_type']=test_input($_POST['delivary_type']);
    $_SESSION['taxidno']=test_input($_POST['taxidno']);
    $_SESSION['height_cm']=test_input($_POST['height_cm']);
    $_SESSION['height_inch']=test_input($_POST['height_inch']);
    $_SESSION['religion']=test_input($_POST['religion']);
    $_SESSION['nameofapplicant']=test_input($_POST['nameofapplicant']);
    $_SESSION['appliemail']=test_input($_POST['appliemail']);
    $_SESSION['givennameofapplicant']=test_input($_POST['givennameofapplicant']);
    $_SESSION['surnnameofapplicant']=test_input($_POST['surnnameofapplicant']);
    $_SESSION['applinationality_place']=test_input($_POST['applinationality_place']);
    $_SESSION['appli_citizenship_status']=test_input($_POST['appli_citizenship_status']);
    $_SESSION['nameoffather']=test_input($_POST['nameoffather']);
    $_SESSION['citizen_ship_type']=test_input($_POST['citizen_ship_type']);
    $_SESSION['father_nationality']=test_input($_POST['father_nationality']);
    $_SESSION['father_profession']=test_input($_POST['father_profession']);
    $_SESSION['nameofmother']=test_input($_POST['nameofmother']);
    $_SESSION['villege/house']=test_input($_POST['villege/house']);
    $_SESSION['mother_nationality']=test_input($_POST['mother_nationality']);
    $_SESSION['road/block/sector']=test_input($_POST['road/block/sector']);
    $_SESSION['mother_profession']=test_input($_POST['mother_profession']);
    $_SESSION['district']=test_input($_POST['district']);
    $_SESSION['nameofspouse']=test_input($_POST['nameofspouse']);
    $_SESSION['police']=test_input($_POST['police']);
    $_SESSION['postoffice']=test_input($_POST['postoffice']);
    $_SESSION['spouse_nationality']=test_input($_POST['spouse_nationality']);
    $_SESSION['spouse_profession']=test_input($_POST['spouse_profession']);
    $_SESSION['marital_status']=test_input($_POST['marital_status']);
    $_SESSION['applicant_profession']=test_input($_POST['applicant_profession']);
    $_SESSION['pmvillege/house']=test_input($_POST['pmvillege/house']);
    $_SESSION['pmroad/block/sector']=test_input($_POST['pmroad/block/sector']);
    $_SESSION['birth_country']=test_input($_POST['birth_country']);
    $_SESSION['pmdistrict']=test_input($_POST['pmdistrict']);
    $_SESSION['birthdistrict']=test_input($_POST['birthdistrict']);
    $_SESSION['pmpolice']=test_input($_POST['pmpolice']);
    $_SESSION['pmpostoffice']=test_input($_POST['pmpostoffice']);
    if(isset($_SESSION['gender']))
        {
            $_SESSION['g']=2;
        }
        if(empty($_SESSION['gender']))
        {
         $_SESSION['g']=1;
        }
        if(isset($_SESSION['dateofbirth']))
        {
            $_SESSION['db']=2;
        }
        if(empty($_SESSION['dateofbirth']))
        {
            $_SESSION['db']=1;
        }
        if(isset($_SESSION['pass_type']))
        {
            $_SESSION['ps']=2;
        }
        if(empty($_SESSION['pass_type']))
        {
            $_SESSION['ps']=1;
        }
        if(isset($_SESSION['birthidno']))
        {
            $_SESSION['bd']=2;
        }
        if(empty($_SESSION['birthidno']))
        {
            $_SESSION['bd']=1;
        }
        if(isset($_SESSION['height_cm']))
        {
            $_SESSION['hcm']=2;
        }
        if(empty($_SESSION['height_cm']))
        {
            $_SESSION['hcm']=1;
        } 
        if(isset($_SESSION['height_inch']))
        {
            $_SESSION['hin']=2;
        }
        if(empty($_SESSION['height_inch']))
        {
            $_SESSION['hin']=1;
        }
        if(isset($_SESSION['religion']))
        {
            $_SESSION['re']=2;
        }
        if(empty($_SESSION['religion']))
        {
            $_SESSION['re']=1;
        }
        if(isset($_SESSION['nameofapplicant']))
        {
            $_SESSION['nam']=2;
        }
        if(empty($_SESSION['nameofapplicant']))
        {
            $_SESSION['nam']=1;
        }
        if(isset($_SESSION['appliemail']))
        {
            $_SESSION['apm']=2;
        }
        if(empty($_SESSION['appliemail']))
        {
            $_SESSION['apm']=1;
        }
        if(isset($_SESSION['surnnameofapplicant']))
        {
            $_SESSION['sp']=2;
        }
        if(empty($_SESSION['surnnameofapplicant']))
        {
            $_SESSION['sp']=1;
        }
        if(isset($_SESSION['nameoffather']))
        {
            $_SESSION['gn']=2;
        }
        if(empty($_SESSION['nameoffather']))
        {
            $_SESSION['gn']=1;
        }
        if(isset($_SESSION['citizen_ship_type']))
        {
            $_SESSION['cit']=2;
        }
        if(empty($_SESSION['citizen_ship_type']))
        {
            $_SESSION['cit']=1;
        }
        if(isset($_SESSION['father_nationality']))
        {
            $_SESSION['fn']=2;
        }
        if(empty($_SESSION['father_nationality']))
        {
            $_SESSION['fn']=1;
        }
        if(isset($_SESSION['father_profession']))
        {
            $_SESSION['fp']=2;
        }
        if(empty($_SESSION['father_profession']))
        {
            $_SESSION['fp']=1;
        }
        if(isset($_SESSION['nameofmother']))
        {
            $_SESSION['mn']=2;
        }
        if(empty($_SESSION['nameofmother']))
        {
            $_SESSION['mn']=1;
        }
        if(isset($_SESSION['mother_nationality']))
        {
            $_SESSION['mni']=2;
        }
        if(empty($_SESSION['mother_nationality']))
        {
            $_SESSION['mni']=1;
        }
        if(isset($_SESSION['mother_profession']))
        {
            $_SESSION['mp']=2;
        }
        if(empty($_SESSION['mother_profession']))
        {
            $_SESSION['mp']=1;
        }
        if(isset($_SESSION['district']))
        {
            $_SESSION['d']=2;
        }
        if(empty($_SESSION['district']))
        {
            $_SESSION['d']=1;
        }
        if(isset($_SESSION['police']))
        {
            $_SESSION['po']=2;
        }
        if(empty($_SESSION['police']))
        {
            $_SESSION['po']=1;
        }
        if(isset($_SESSION['postoffice']))
        {
            $_SESSION['pos']=2;
        }
        if(empty($_SESSION['postoffice']))
        {
            $_SESSION['pos']=1;
        }
        if(isset($_SESSION['marital_status']))
        {
            $_SESSION['mts']=2;
        }
        if(empty($_SESSION['marital_status']))
        {
            $_SESSION['mts']=1;
        }
        if(isset($_SESSION['applicant_profession']))
        {
            $_SESSION['apf']=2;
        }
        if(empty($_SESSION['applicant_profession']))
        {
            $_SESSION['apf']=1;
        }
        if(isset($_SESSION['birth_country']))
        {
            $_SESSION['brc']=2;
        }
        if(empty($_SESSION['birth_country']))
        {
            $_SESSION['brc']=1;
        }
        if(isset($_SESSION['pmdistrict']))
        {
            $_SESSION['pmdis']=2;
        }
        if(empty($_SESSION['pmdistrict']))
        {
            $_SESSION['pmdis']=1;
        }
        if(isset($_SESSION['birthdistrict']))
        {
            $_SESSION['bdd']=2;
        }
        if(empty($_SESSION['birthdistrict']))
        {
            $_SESSION['bdd']=1;
        }
        if(isset($_SESSION['pmpolice']))
        {
            $_SESSION['pp']=2;
        }
        if(empty($_SESSION['pmpolice']))
        {
            $_SESSION['pp']=1;
        }
        if(isset($_SESSION['pmpostoffice']))
        {
            $_SESSION['ppos']=2;
        }
        if(empty($_SESSION['pmpostoffice']))
        {
            $_SESSION['ppos']=1;
        }
    function test_input($data) 
    {
        $data = trim($data);
        $data = stripslashes($data);
        $data = htmlspecialchars($data);
        return $data;
    }
    if($_SESSION['s1']==1)
    {
        header('Location:stage2ver2.php');
    }
    else
    {
        header('Location:stage2.php');
    }
    
?>