<?php
    session_start();
    $_SESSION['s2'];

    $_SESSION['officeno']=test_input($_POST['officeno']);
    $_SESSION['passportno']=test_input($_POST['passportno']);
    $_SESSION['residenceno']=test_input($_POST['residenceno']);
    $_SESSION['placeofissue']=test_input($_POST['placeofissue']);
    $_SESSION['mobileno']=test_input($_POST['mobileno']);
    $_SESSION['dateofissue']=test_input($_POST['dateofissue']);
    $_SESSION['reissuereason']=test_input($_POST['reissuereason']);
    $_SESSION['emcontactname']=test_input($_POST['emcontactname']);
    $_SESSION['em_country']=test_input($_POST['em_country']);
    $_SESSION['emvillege/house']=test_input($_POST['emvillege/house']);
    $_SESSION['emroad/block/sector']=test_input($_POST['emroad/block/sector']);
    $_SESSION['emdistrict']=test_input($_POST['emdistrict']);
    $_SESSION['empolice']=test_input($_POST['empolice']);
    $_SESSION['empostoffice']=test_input($_POST['empostoffice']);
    $_SESSION['emcontactno']=test_input($_POST['emcontactno']);
    $_SESSION['ememail']=test_input($_POST['ememail']);
    $_SESSION['emrelations']=test_input($_POST['emrelation']);
    if(isset($_SESSION['emcontactname']))
        {
            $_SESSION['emn']=2;
        }
        if(empty($_SESSION['emcontactname']))
        {
         $_SESSION['emn']=1;
        }
        if(isset($_SESSION['em_country']))
        {
            $_SESSION['emc']=2;
        }
        if(empty($_SESSION['em_country']))
        {
            $_SESSION['emc']=1;
        }
        if(isset($_SESSION['emdistrict']))
        {
            $_SESSION['emd']=2;
        }
        if(empty($_SESSION['emdistrict']))
        {
            $_SESSION['emd']=1;
        }
        if(isset($_SESSION['empolice']))
        {
            $_SESSION['emp']=2;
        }
        if(empty($_SESSION['empolice']))
        {
            $_SESSION['emp']=1;
        }
        if(isset($_SESSION['empostoffice']))
        {
            $_SESSION['empos']=2;
        }
        if(empty($_SESSION['empostoffice']))
        {
            $_SESSION['empos']=1;
        }
        if(isset($_SESSION['emcontactno']))
        {
            $_SESSION['emcon']=2;
        }
        if(empty($_SESSION['emcontactno']))
        {
            $_SESSION['emcon']=1;
        }
        if(isset($_SESSION['ememail']))
        {
            $_SESSION['eme']=2;
        }
        if(empty($_SESSION['ememail']))
        {
            $_SESSION['eme']=1;
        }
        if(isset($_SESSION['emrelation']))
        {
            $_SESSION['emre']=2;
        }
        if(empty($_SESSION['emrelation']))
        {
            $_SESSION['emre']=1;
        }
    function test_input($data) 
    {
        $data = trim($data);
        $data = stripslashes($data);
        $data = htmlspecialchars($data);
        return $data;
    }
    if($_SESSION['s2']==1)
    {
        header('Location:stage3ver2.php');
    }
    else
    {
        header('Location:stage3.php');
    }
    
?>