
<?php
        session_start();
        if(isset($_SESSION['gender']))
        {
            $_SESSION['g']=2;
        }
        if(empty($_SESSION['gender']))
        {
         $_SESSION['g']=1;
        }
        if(isset($_SESSION['dateofbirth']))
        {
            $_SESSION['db']=2;
        }
        if(empty($_SESSION['dateofbirth']))
        {
            $_SESSION['db']=1;
        }
        if(isset($_SESSION['pass_type']))
        {
            $_SESSION['ps']=2;
        }
        if(empty($_SESSION['pass_type']))
        {
            $_SESSION['ps']=1;
        }
        if(isset($_SESSION['birthidno']))
        {
            $_SESSION['bd']=2;
        }
        if(empty($_SESSION['birthidno']))
        {
            $_SESSION['bd']=1;
        }
        if(isset($_SESSION['height_cm']))
        {
            $_SESSION['hcm']=2;
        }
        if(empty($_SESSION['height_cm']))
        {
            $_SESSION['hcm']=1;
        } 
        if(isset($_SESSION['height_inch']))
        {
            $_SESSION['hin']=2;
        }
        if(empty($_SESSION['height_inch']))
        {
            $_SESSION['hin']=1;
        }
        if(isset($_SESSION['religion']))
        {
            $_SESSION['re']=2;
        }
        if(empty($_SESSION['religion']))
        {
            $_SESSION['re']=1;
        }
        if(isset($_SESSION['nameofapplicant']))
        {
            $_SESSION['nam']=2;
        }
        if(empty($_SESSION['nameofapplicant']))
        {
            $_SESSION['nam']=1;
        }
        if(isset($_SESSION['appliemail']))
        {
            $_SESSION['apm']=2;
        }
        if(empty($_SESSION['appliemail']))
        {
            $_SESSION['apm']=1;
        }
        if(isset($_SESSION['surnnameofapplicant']))
        {
            $_SESSION['sp']=2;
        }
        if(empty($_SESSION['surnnameofapplicant']))
        {
            $_SESSION['sp']=1;
        }
        if(isset($_SESSION['nameoffather']))
        {
            $_SESSION['gn']=2;
        }
        if(empty($_SESSION['nameoffather']))
        {
            $_SESSION['gn']=1;
        }
        if(isset($_SESSION['citizen_ship_type']))
        {
            $_SESSION['cit']=2;
        }
        if(empty($_SESSION['citizen_ship_type']))
        {
            $_SESSION['cit']=1;
        }
        if(isset($_SESSION['father_nationality']))
        {
            $_SESSION['fn']=2;
        }
        if(empty($_SESSION['father_nationality']))
        {
            $_SESSION['fn']=1;
        }
        if(isset($_SESSION['father_profession']))
        {
            $_SESSION['fp']=2;
        }
        if(empty($_SESSION['father_profession']))
        {
            $_SESSION['fp']=1;
        }
        if(isset($_SESSION['nameofmother']))
        {
            $_SESSION['mn']=2;
        }
        if(empty($_SESSION['nameofmother']))
        {
            $_SESSION['mn']=1;
        }
        if(isset($_SESSION['mother_nationality']))
        {
            $_SESSION['mni']=2;
        }
        if(empty($_SESSION['mother_nationality']))
        {
            $_SESSION['mni']=1;
        }
        if(isset($_SESSION['mother_profession']))
        {
            $_SESSION['mp']=2;
        }
        if(empty($_SESSION['mother_profession']))
        {
            $_SESSION['mp']=1;
        }
        if(isset($_SESSION['district']))
        {
            $_SESSION['d']=2;
        }
        if(empty($_SESSION['district']))
        {
            $_SESSION['d']=1;
        }
        if(isset($_SESSION['police']))
        {
            $_SESSION['po']=2;
        }
        if(empty($_SESSION['police']))
        {
            $_SESSION['po']=1;
        }
        if(isset($_SESSION['postoffice']))
        {
            $_SESSION['pos']=2;
        }
        if(empty($_SESSION['postoffice']))
        {
            $_SESSION['pos']=1;
        }
        if(isset($_SESSION['marital_status']))
        {
            $_SESSION['mts']=2;
        }
        if(empty($_SESSION['marital_status']))
        {
            $_SESSION['mts']=1;
        }
        if(isset($_SESSION['applicant_profession']))
        {
            $_SESSION['apf']=2;
        }
        if(empty($_SESSION['applicant_profession']))
        {
            $_SESSION['apf']=1;
        }
        if(isset($_SESSION['birth_country']))
        {
            $_SESSION['brc']=2;
        }
        if(empty($_SESSION['birth_country']))
        {
            $_SESSION['brc']=1;
        }
        if(isset($_SESSION['pmdistrict']))
        {
            $_SESSION['pmdis']=2;
        }
        if(empty($_SESSION['pmdistrict']))
        {
            $_SESSION['pmdis']=1;
        }
        if(isset($_SESSION['birthdistrict']))
        {
            $_SESSION['bdd']=2;
        }
        if(empty($_SESSION['birthdistrict']))
        {
            $_SESSION['bdd']=1;
        }
        if(isset($_SESSION['pmpolice']))
        {
            $_SESSION['pp']=2;
        }
        if(empty($_SESSION['pmpolice']))
        {
            $_SESSION['pp']=1;
        }
        if(isset($_SESSION['pmpostoffice']))
        {
            $_SESSION['ppos']=2;
        }
        if(empty($_SESSION['pmpostoffice']))
        {
            $_SESSION['ppos']=1;
        }
        if($_SESSION['g']==1||$_SESSION['db']==1||$_SESSION['ps']==1||$_SESSION['bd']==1||$_SESSION['hin']==1||$_SESSION['hcm']==1||$_SESSION['re']==1||$_SESSION['nam']==1||$_SESSION['apm']==1||$_SESSION['sp']==1||$_SESSION['gn']==1||$_SESSION['cit']==1||$_SESSION['fn']==1||$_SESSION['fp']==1||$_SESSION['mn']==1||$_SESSION['mni']==1||$_SESSION['mp']==1||$_SESSION['d']==1||$_SESSION['po']==1||$_SESSION['pos']==1||$_SESSION['mts']==1||$_SESSION['apf']==1||$_SESSION['brc']==1||$_SESSION['pmdis']==1||$_SESSION['bdd']==1||$_SESSION['pp']==1||$_SESSION['ppos']==1)
        {
            $_SESSION['Flag 1']=1;
        }
        if(isset($_SESSION['emcontactname']))
        {
            $_SESSION['emn']=2;
        }
        if(empty($_SESSION['emcontactname']))
        {
         $_SESSION['emn']=1;
        }
        if(isset($_SESSION['em_country']))
        {
            $_SESSION['emc']=2;
        }
        if(empty($_SESSION['em_country']))
        {
            $_SESSION['emc']=1;
        }
        if(isset($_SESSION['emdistrict']))
        {
            $_SESSION['emd']=2;
        }
        if(empty($_SESSION['emdistrict']))
        {
            $_SESSION['emd']=1;
        }
        if(isset($_SESSION['empolice']))
        {
            $_SESSION['emp']=2;
        }
        if(empty($_SESSION['empolice']))
        {
            $_SESSION['emp']=1;
        }
        if(isset($_SESSION['empostoffice']))
        {
            $_SESSION['empos']=2;
        }
        if(empty($_SESSION['empostoffice']))
        {
            $_SESSION['empos']=1;
        }
        if(isset($_SESSION['emcontactno']))
        {
            $_SESSION['emcon']=2;
        }
        if(empty($_SESSION['emcontactno']))
        {
            $_SESSION['emcon']=1;
        }
        if(isset($_SESSION['ememail']))
        {
            $_SESSION['eme']=2;
        }
        if(empty($_SESSION['ememail']))
        {
            $_SESSION['eme']=1;
        }
        if(isset($_SESSION['emrelatio']))
        {
            $_SESSION['emre']=2;
        }
        if(empty($_SESSION['emrelatio']))
        {
            $_SESSION['emre']=1;
        }
        if($_SESSION['emn']==1||$_SESSION['emc']==1||$_SESSION['emd']==1||$_SESSION['emp']==1||$_SESSION['empos']==1||$_SESSION['emcon']==1||$_SESSION['eme']==1||$_SESSION['emre']==1)
        {
            $_SESSION['Flag 2']=1;
        }
        if(isset($_SESSION['currency']))
        {
            $_SESSION['ccn']=2;
        }
        if(empty($_SESSION['skippay']))
        {
            $_SESSION['skp']=1;
        }
        if(isset($_SESSION['skippay']))
        {
            $_SESSION['skp']=2;
        }
        if(empty($_SESSION['currency']))
        {
            $_SESSION['ccn']=1;
        }
        if(isset($_SESSION['amount']))
        {
            $_SESSION['ammn']=2;
        }
        if(empty($_SESSION['amount']))
        {
            $_SESSION['ammn']=1;
        }
        if(isset($_SESSION['emrelation']))
        {
            $_SESSION['emre']=2;
        }
        if(empty($_SESSION['paymentdate']))
        {
            $_SESSION['dap']=1;
        }
        if(isset($_SESSION['paymentdate']))
        {
            $_SESSION['dap']=2;
        }
        if(empty($_SESSION['receiptno']))
        {
            $_SESSION['rep']=1;
        }
        if(isset($_SESSION['receiptno']))
        {
            $_SESSION['rep']=2;
        }
        if($_SESSION['ccn']==1||$_SESSION['ammn']==1||$_SESSION['dap']==1||$_SESSION['rep']==1)
        {
            $_SESSION['Flag 3']=1;
        }     
        header('Location:validateresult.php');
        $_SESSION[s3]=1;
?>
        

